// @datatr-ux/uxlib/tailwind.preset.js
export default {
  theme: {
    extend: {
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
      colors: {
        // background: "var(--background, var(--ods-color-white), #fff)",
        foreground: "var(--foreground, var(--ods-color-text))",
        card: {
          DEFAULT: "var(--card, var(--ods-color-white))",
          foreground: "var(--card-foreground, var(--ods-color-text))",
        },
        popover: {
          DEFAULT: "var(--popover, var(--ods-color-white))",
          foreground: "var(--popover-foreground, var(--ods-color-text))",
        },
        primary: {
          DEFAULT: "var(--primary, var(--ods-color-primary-500))",
          foreground: "var(--primary-foreground, var(--ods-color-white))",
        },
        secondary: {
          DEFAULT: "var(--secondary, var(--ods-color-neutral-050))",
          foreground: "var(--secondary-foreground, var(--ods-color-neutral-700))",
        },
        muted: {
          DEFAULT: "var(--muted, var(--ods-color-neutral-050))",
          foreground: "var(--muted-foreground, var(--ods-color-neutral-500))",
        },
        accent: {
          DEFAULT: "var(--accent, var(--ods-color-primary-050))",
          foreground: "var(--accent-foreground, var(--ods-color-text))",
        },
        destructive: {
          DEFAULT: "var(--destructive, var(--ods-color-critical-500))",
          foreground: "var(--destructive-foreground, var(--ods-color-white))",
        },
        // border: "var(--border, var(--ods-color-neutral-100))",
        input: "var(--input, var(--ods-color-neutral-100))",
        ring: "var(--ring, var(--ods-outline-color-default))",

        chart: {
          1: "hsl(var(--chart-1, 12 76% 61%))",
          2: "hsl(var(--chart-2, 173 58% 39%))",
          3: "hsl(var(--chart-3, 197 37% 24%))",
          4: "hsl(var(--chart-4, 43 74% 66%))",
          5: "hsl(var(--chart-5, 27 87% 67%))",
        },

        sidebar: {
          DEFAULT: "var(--sidebar-background, var(--ods-color-white))",
          foreground: "var(--sidebar-foreground, var(--ods-color-text))",
          primary: "var(--sidebar-primary, var(--ods-color-primary-500))",
          "primary-foreground": "var(--sidebar-primary-foreground, var(--ods-color-white))",
          accent: "var(--sidebar-accent, var(--ods-color-primary-050))",
          "accent-foreground": "var(--sidebar-accent-foreground, var(--ods-color-text))",
          border: "var(--sidebar-border, var(--ods-color-neutral-100))",
          ring: "var(--sidebar-ring, var(--ods-outline-color-default))",
        },

        transparent: "#FFFFFF00",
        blue: {
          DEFAULT: "var(--ods-color-primary-500)",
          0: "var(--ods-color-primary-000)",
          25: "var(--ods-color-primary-025)",
          50: "var(--ods-color-primary-050)",
          75: "var(--ods-color-primary-075)",
          100: "var(--ods-color-primary-100)",
          200: "var(--ods-color-primary-200)",
          300: "var(--ods-color-primary-300)",
          400: "var(--ods-color-primary-400)",
          500: "var(--ods-color-primary-500)",
          600: "var(--ods-color-primary-600)",
          700: "var(--ods-color-primary-700)",
          800: "var(--ods-color-primary-800)",
          900: "var(--ods-color-primary-900)",
        },
        primary: {
          DEFAULT: "var(--ods-color-primary-500)",
          0: "var(--ods-color-primary-000)",
          25: "var(--ods-color-primary-025)",
          50: "var(--ods-color-primary-050)",
          75: "var(--ods-color-primary-075)",
          100: "var(--ods-color-primary-100)",
          200: "var(--ods-color-primary-200)",
          300: "var(--ods-color-primary-300)",
          400: "var(--ods-color-primary-400)",
          500: "var(--ods-color-primary-500)",
          600: "var(--ods-color-primary-600)",
          700: "var(--ods-color-primary-700)",
          800: "var(--ods-color-primary-800)",
          900: "var(--ods-color-primary-900)",
        },
        neutral: {
          DEFAULT: "var(--ods-color-neutral-500)",
          0: "var(--ods-color-neutral-000)",
          25: "var(--ods-color-neutral-025)",
          50: "var(--ods-color-neutral-050)",
          75: "var(--ods-color-neutral-075)",
          100: "var(--ods-color-neutral-100)",
          200: "var(--ods-color-neutral-200)",
          300: "var(--ods-color-neutral-300)",
          400: "var(--ods-color-neutral-400)",
          500: "var(--ods-color-neutral-500)",
          600: "var(--ods-color-neutral-600)",
          700: "var(--ods-color-neutral-700)",
          800: "var(--ods-color-neutral-800)",
          900: "var(--ods-color-neutral-900)",
        },
        gray: {
          DEFAULT: "var(--ods-color-neutral-500)",
          0: "var(--ods-color-neutral-000)",
          25: "var(--ods-color-neutral-025)",
          50: "var(--ods-color-neutral-050)",
          75: "var(--ods-color-neutral-075)",
          100: "var(--ods-color-neutral-100)",
          200: "var(--ods-color-neutral-200)",
          300: "var(--ods-color-neutral-300)",
          400: "var(--ods-color-neutral-400)",
          500: "var(--ods-color-neutral-500)",
          600: "var(--ods-color-neutral-600)",
          700: "var(--ods-color-neutral-700)",
          800: "var(--ods-color-neutral-800)",
          900: "var(--ods-color-neutral-900)",
        },
        success: {
          DEFAULT: "var(--ods-color-success-500)",
          0: "var(--ods-color-success-000)",
          25: "var(--ods-color-success-025)",
          50: "var(--ods-color-success-050)",
          75: "var(--ods-color-success-075)",
          100: "var(--ods-color-success-100)",
          200: "var(--ods-color-success-200)",
          300: "var(--ods-color-success-300)",
          400: "var(--ods-color-success-400)",
          500: "var(--ods-color-success-500)",
          600: "var(--ods-color-success-600)",
          700: "var(--ods-color-success-700)",
          800: "var(--ods-color-success-800)",
          900: "var(--ods-color-success-900)",
        },
        green: {
          DEFAULT: "var(--ods-color-success-500)",
          0: "var(--ods-color-success-000)",
          25: "var(--ods-color-success-025)",
          50: "var(--ods-color-success-050)",
          75: "var(--ods-color-success-075)",
          100: "var(--ods-color-success-100)",
          200: "var(--ods-color-success-200)",
          300: "var(--ods-color-success-300)",
          400: "var(--ods-color-success-400)",
          500: "var(--ods-color-success-500)",
          600: "var(--ods-color-success-600)",
          700: "var(--ods-color-success-700)",
          800: "var(--ods-color-success-800)",
          900: "var(--ods-color-success-900)",
        },
        warning: {
          DEFAULT: "var(--ods-color-warning-500)",
          0: "var(--ods-color-warning-000)",
          25: "var(--ods-color-warning-025)",
          50: "var(--ods-color-warning-050)",
          75: "var(--ods-color-warning-075)",
          100: "var(--ods-color-warning-100)",
          200: "var(--ods-color-warning-200)",
          300: "var(--ods-color-warning-300)",
          400: "var(--ods-color-warning-400)",
          500: "var(--ods-color-warning-500)",
          600: "var(--ods-color-warning-600)",
          700: "var(--ods-color-warning-700)",
          800: "var(--ods-color-warning-800)",
          900: "var(--ods-color-warning-900)",
        },
        yellow: {
          DEFAULT: "var(--ods-color-warning-500)",
          0: "var(--ods-color-warning-000)",
          25: "var(--ods-color-warning-025)",
          50: "var(--ods-color-warning-050)",
          75: "var(--ods-color-warning-075)",
          100: "var(--ods-color-warning-100)",
          200: "var(--ods-color-warning-200)",
          300: "var(--ods-color-warning-300)",
          400: "var(--ods-color-warning-400)",
          500: "var(--ods-color-warning-500)",
          600: "var(--ods-color-warning-600)",
          700: "var(--ods-color-warning-700)",
          800: "var(--ods-color-warning-800)",
          900: "var(--ods-color-warning-900)",
        },
        critical: {
          DEFAULT: "var(--ods-color-critical-500)",
          0: "var(--ods-color-critical-000)",
          25: "var(--ods-color-critical-025)",
          50: "var(--ods-color-critical-050)",
          75: "var(--ods-color-critical-075)",
          100: "var(--ods-color-critical-100)",
          200: "var(--ods-color-critical-200)",
          300: "var(--ods-color-critical-300)",
          400: "var(--ods-color-critical-400)",
          500: "var(--ods-color-critical-500)",
          600: "var(--ods-color-critical-600)",
          700: "var(--ods-color-critical-700)",
          800: "var(--ods-color-critical-800)",
          900: "var(--ods-color-critical-900)",
        },
        red: {
          DEFAULT: "var(--ods-color-critical-500)",
          0: "var(--ods-color-critical-000)",
          25: "var(--ods-color-critical-025)",
          50: "var(--ods-color-critical-050)",
          75: "var(--ods-color-critical-075)",
          100: "var(--ods-color-critical-100)",
          200: "var(--ods-color-critical-200)",
          300: "var(--ods-color-critical-300)",
          400: "var(--ods-color-critical-400)",
          500: "var(--ods-color-critical-500)",
          600: "var(--ods-color-critical-600)",
          700: "var(--ods-color-critical-700)",
          800: "var(--ods-color-critical-800)",
          900: "var(--ods-color-critical-900)",
        },
        information: {
          DEFAULT: "var(--ods-color-information-500)",
          0: "var(--ods-color-information-000)",
          25: "var(--ods-color-information-025)",
          50: "var(--ods-color-information-050)",
          75: "var(--ods-color-information-075)",
          100: "var(--ods-color-information-100)",
          200: "var(--ods-color-information-200)",
          300: "var(--ods-color-information-300)",
          400: "var(--ods-color-information-400)",
          500: "var(--ods-color-information-500)",
          600: "var(--ods-color-information-600)",
          700: "var(--ods-color-information-700)",
          800: "var(--ods-color-information-800)",
          900: "var(--ods-color-information-900)",
        },
        lightBlue: {
          DEFAULT: "var(--ods-color-information-500)",
          0: "var(--ods-color-information-000)",
          25: "var(--ods-color-information-025)",
          50: "var(--ods-color-information-050)",
          75: "var(--ods-color-information-075)",
          100: "var(--ods-color-information-100)",
          200: "var(--ods-color-information-200)",
          300: "var(--ods-color-information-300)",
          400: "var(--ods-color-information-400)",
          500: "var(--ods-color-information-500)",
          600: "var(--ods-color-information-600)",
          700: "var(--ods-color-information-700)",
          800: "var(--ods-color-information-800)",
          900: "var(--ods-color-information-900)",
        },
        brand: {
          master: "var(--ods-color-brand-masterbrand)",
          darkBlue: "var(--ods-color-brand-dark-blue)",
          green: "var(--ods-color-brand-green)",
          orange: "var(--ods-color-brand-orange)",
          skyblue: "var(--ods-color-brand-skyblue)",
          yellow: "var(--ods-color-brand-yellow)",
        },
        text: {
          DEFAULT: "var(--ods-color-text)",
          disabled: "var(--ods-color-text-disabled-default)",
          selected: "var(--ods-color-element-text-selected)",
        },
        background: {
          DEFAULT: "var(--background, var(--ods-color-white), #fff)",
          disabled: "var(--ods-color-background-disabled-default)",
          readonly: "var(--ods-color-background-readonly-default)",
          selected: "var(--ods-color-element-background-selected)",
        },
        border: {
          DEFAULT: "var(--border, var(--ods-color-neutral-100))",
          disabled: "var(--ods-color-border-disabled-default)",
          readonly: "var(--ods-color-border-readonly-default)",
          critical: "var(--ods-color-form-element-border-critical)",
        },
        alpha: "var(--ods-color-alpha)",
        beta: "var(--ods-color-beta)",
        eco: "var(--ods-color-eco)",
        limited: "var(--ods-color-limited)",
        new: "var(--ods-color-new)",
        promotion: "var(--ods-color-promotion)",
        heading: "var(--ods-color-heading)",
      },

      borderRadius: {
        xs: "var(--ods-border-radius-xs)",
        sm: "var(--ods-border-radius-sm)",
        md: "var(--ods-border-radius-md)",
        lg: "var(--ods-border-radius-lg)",
      },

      borderWidth: {
        sm: "var(--ods-border-width-sm)",
        md: "var(--ods-border-width-md)",
      },

      transitionDuration: {
        DEFAULT: "var(--ods-transition-duration-default)",
      },

      outlineOffset: {
        DEFAULT: "var(--ods-outline-offset)",
      },

      outlineWidth: {
        DEFAULT: "var(--ods-outline-width)",
      },

      outlineColor: {
        DEFAULT: "var(--ods-outline-color-default)",
      },

      fontSize: {
        xs: "0.75rem",   // 12px (caption)
        sm: "0.875rem",  // 14px
        base: "1rem",    // 16px
        lg: "1.125rem",  // 18px
        xl: "1.25rem",   // 20px
        "2xl": "1.5rem", // 24px
        "3xl": "1.75rem",// 28px
        "4xl": "2.25rem" // 36px
      },

      fontWeight: {
        normal: "400",
        semibold: "600",
        bold: "700",
      },

      // screens: {
      //   "xs": "var(--ods-breakpoint-sub-mobile)",
      //   sm: "var(--ods-breakpoint-mobile)",
      //   md: "var(--ods-breakpoint-tablet)",
      //   lg: "var(--ods-breakpoint-desktop)",
      //   "xl": "var(--ods-breakpoint-large-screen)",
      //   '2xl': "var(--ods-breakpoint-widescreen)",
      // },
    },
  },
};
