// @datatr-ux/uxlib/tailwind.preset.js
export default {
  theme: {
    extend: {
      colors: {
        primary: {
          DEFAULT: "var(--ods-color-primary-500)",
          0: "var(--ods-color-primary-000)",
          25: "var(--ods-color-primary-025)",
          50: "var(--ods-color-primary-050)",
          75: "var(--ods-color-primary-075)",
          100: "var(--ods-color-primary-100)",
          200: "var(--ods-color-primary-200)",
          300: "var(--ods-color-primary-300)",
          400: "var(--ods-color-primary-400)",
          500: "var(--ods-color-primary-500)",
          600: "var(--ods-color-primary-600)",
          700: "var(--ods-color-primary-700)",
          800: "var(--ods-color-primary-800)",
          900: "var(--ods-color-primary-900)",
        },
        neutral: {
          DEFAULT: "var(--ods-color-neutral-500)",
          0: "var(--ods-color-neutral-000)",
          25: "var(--ods-color-neutral-025)",
          50: "var(--ods-color-neutral-050)",
          75: "var(--ods-color-neutral-075)",
          100: "var(--ods-color-neutral-100)",
          200: "var(--ods-color-neutral-200)",
          300: "var(--ods-color-neutral-300)",
          400: "var(--ods-color-neutral-400)",
          500: "var(--ods-color-neutral-500)",
          600: "var(--ods-color-neutral-600)",
          700: "var(--ods-color-neutral-700)",
          800: "var(--ods-color-neutral-800)",
          900: "var(--ods-color-neutral-900)",
        },
        gray: {
          DEFAULT: "var(--ods-color-neutral-500)",
          0: "var(--ods-color-neutral-000)",
          25: "var(--ods-color-neutral-025)",
          50: "var(--ods-color-neutral-050)",
          75: "var(--ods-color-neutral-075)",
          100: "var(--ods-color-neutral-100)",
          200: "var(--ods-color-neutral-200)",
          300: "var(--ods-color-neutral-300)",
          400: "var(--ods-color-neutral-400)",
          500: "var(--ods-color-neutral-500)",
          600: "var(--ods-color-neutral-600)",
          700: "var(--ods-color-neutral-700)",
          800: "var(--ods-color-neutral-800)",
          900: "var(--ods-color-neutral-900)",
        },
        success: {
          DEFAULT: "var(--ods-color-success-500)",
          0: "var(--ods-color-success-000)",
          25: "var(--ods-color-success-025)",
          50: "var(--ods-color-success-050)",
          75: "var(--ods-color-success-075)",
          100: "var(--ods-color-success-100)",
          200: "var(--ods-color-success-200)",
          300: "var(--ods-color-success-300)",
          400: "var(--ods-color-success-400)",
          500: "var(--ods-color-success-500)",
          600: "var(--ods-color-success-600)",
          700: "var(--ods-color-success-700)",
          800: "var(--ods-color-success-800)",
          900: "var(--ods-color-success-900)",
        },
        warning: {
          DEFAULT: "var(--ods-color-warning-500)",
          0: "var(--ods-color-warning-000)",
          25: "var(--ods-color-warning-025)",
          50: "var(--ods-color-warning-050)",
          75: "var(--ods-color-warning-075)",
          100: "var(--ods-color-warning-100)",
          200: "var(--ods-color-warning-200)",
          300: "var(--ods-color-warning-300)",
          400: "var(--ods-color-warning-400)",
          500: "var(--ods-color-warning-500)",
          600: "var(--ods-color-warning-600)",
          700: "var(--ods-color-warning-700)",
          800: "var(--ods-color-warning-800)",
          900: "var(--ods-color-warning-900)",
        },
        critical: {
          DEFAULT: "var(--ods-color-critical-500)",
          0: "var(--ods-color-critical-000)",
          25: "var(--ods-color-critical-025)",
          50: "var(--ods-color-critical-050)",
          75: "var(--ods-color-critical-075)",
          100: "var(--ods-color-critical-100)",
          200: "var(--ods-color-critical-200)",
          300: "var(--ods-color-critical-300)",
          400: "var(--ods-color-critical-400)",
          500: "var(--ods-color-critical-500)",
          600: "var(--ods-color-critical-600)",
          700: "var(--ods-color-critical-700)",
          800: "var(--ods-color-critical-800)",
          900: "var(--ods-color-critical-900)",
        },
        information: {
          DEFAULT: "var(--ods-color-information-500)",
          0: "var(--ods-color-information-000)",
          25: "var(--ods-color-information-025)",
          50: "var(--ods-color-information-050)",
          75: "var(--ods-color-information-075)",
          100: "var(--ods-color-information-100)",
          200: "var(--ods-color-information-200)",
          300: "var(--ods-color-information-300)",
          400: "var(--ods-color-information-400)",
          500: "var(--ods-color-information-500)",
          600: "var(--ods-color-information-600)",
          700: "var(--ods-color-information-700)",
          800: "var(--ods-color-information-800)",
          900: "var(--ods-color-information-900)",
        },
        brand: {
          master: "var(--ods-color-brand-masterbrand)",
          darkBlue: "var(--ods-color-brand-dark-blue)",
          green: "var(--ods-color-brand-green)",
          orange: "var(--ods-color-brand-orange)",
          skyblue: "var(--ods-color-brand-skyblue)",
          yellow: "var(--ods-color-brand-yellow)",
        },
        text: {
          DEFAULT: "var(--ods-color-text)",
          disabled: "var(--ods-color-text-disabled-default)",
          selected: "var(--ods-color-element-text-selected)",
        },
        background: {
          disabled: "var(--ods-color-background-disabled-default)",
          readonly: "var(--ods-color-background-readonly-default)",
          selected: "var(--ods-color-element-background-selected)",
        },
        border: {
          disabled: "var(--ods-color-border-disabled-default)",
          readonly: "var(--ods-color-border-readonly-default)",
          critical: "var(--ods-color-form-element-border-critical)",
        },
        alpha: "var(--ods-color-alpha)",
        beta: "var(--ods-color-beta)",
        eco: "var(--ods-color-eco)",
        limited: "var(--ods-color-limited)",
        new: "var(--ods-color-new)",
        promotion: "var(--ods-color-promotion)",
        heading: "var(--ods-color-heading)",
      },

      borderRadius: {
        xs: "var(--ods-border-radius-xs)",
        sm: "var(--ods-border-radius-sm)",
        md: "var(--ods-border-radius-md)",
        lg: "var(--ods-border-radius-lg)",
      },

      borderWidth: {
        sm: "var(--ods-border-width-sm)",
        md: "var(--ods-border-width-md)",
      },

      transitionDuration: {
        DEFAULT: "var(--ods-transition-duration-default)",
      },

      outlineOffset: {
        DEFAULT: "var(--ods-outline-offset)",
      },

      outlineWidth: {
        DEFAULT: "var(--ods-outline-width)",
      },

      outlineColor: {
        DEFAULT: "var(--ods-outline-color-default)",
      },

      screens: {
        "sub-mobile": "var(--ods-breakpoint-sub-mobile)",
        mobile: "var(--ods-breakpoint-mobile)",
        tablet: "var(--ods-breakpoint-tablet)",
        desktop: "var(--ods-breakpoint-desktop)",
        "large-screen": "var(--ods-breakpoint-large-screen)",
        widescreen: "var(--ods-breakpoint-widescreen)",
      },
    },
  },
};
